### ISSUE TITLE
Final Input Checks and XSS Checks

### ISSUE THREAD

**Issue by johnnywong30** [johnnywong30/Pooler#83]
Data Files
- [x] carpools
- [x] comments
- [x] events
- [x] history
- [x] users

Server Files
- [x] auth
- [x] events
- [x] history
- [x] pool
- [x] profile

Client Files
- [x] error
- [x] eventList
- [x] historyList
- [x] pool
- [x] poolList
- [x] validateEvent
- [x] validateLogin
- [x] validatePool
- [x] validateProfile
- [x] validateRegister

**Comment by iFallenDawn** [comment]
validate pool does nothing so removed
